channels:
  - conda-forge
dependencies:
  - r-base=4.1.1
  - r-irkernel=1.2
  - r-tidyverse
  - r-xlsx
  - r-haven
  - r-gghighlight
  - r-ggExtra
  - r-ggridges
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-ragg
  - r-rgeos
  - r-ggalluvial
  - r-treemapify
  - r-xaringan
  - r-kableExtra
  - r-formatR
  - r-ggbump
  - r-dendextend
  - r-ggdendro
  - r-remotes
  - r-rstan
  - r-estimatr
  - r-margins
  - r-summarytools
  - r-gt
