channels:
  - conda-forge
dependencies:
  - r-base=4.1
  - r-irkernel
  - r-tidyverse
  - r-xlsx
  - r-haven
  - r-remotes
  # R Markdown
  - r-rmarkdown
  - r-formatR
  - r-summarytools
  - r-gt
  - r-kableExtra
  - r-bookdown
  - r-xaringan
  # Estimation
  - r-rstan
  - r-estimatr
  - r-margins
  - r-prediction
  # Visualization
  - r-ggpubr
  - r-gghighlight
  - r-ggExtra
  - r-ggridges
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-ragg
  - r-rgeos
  - r-ggalluvial
  - r-treemapify
  - r-ggbump
  - r-dendextend
  - r-ggdendro
  - r-ggmosaic
