channels:
  - conda-forge
dependencies:
  - r-base=4.0.3
  - r-tidyverse
  - r-xlsx
  - r-haven
  - r-gghighlight
  - r-ghibli
  - r-ggridge
  - r-ggExtra
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-rgeos
  - r-daggity
  - r-ggdag
  - r-ggalluvial
  - r-treemapify
  - r-titanic
  - r-rdrobust
  - r-rdd
  - r-xaringan
  - r-kableExtra
  - r-ggbump
  - r-dendextend
  - r-ggdendro
  - r-remotes
  - r-rstan
  - r-estimatr
  - r-margins
